name: build-and-deploy
on:
  push:
    branches:
      - master
    paths:
      - pkgs/**
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Build changed packages
        run: ./scripts/build_changed.sh > manifest.txt

      - name: Upload archives to R2
        uses: ryand56/r2-upload-action@v1
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT }}
          r2-access-key-id: ${{ secrets.R2_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./zigsmith-out
          destination-dir: .

      - name: Update database
        run: |
          while read -r hash name version; do
            curl --fail -X POST "${{ secrets.ZS_URL }}/api/builds" \
              -H "Authorization: Bearer ${{ secrets.ZS_KEY }}" \
              -H "Content-Type: application/json" \
              -d "{\"hash\":\"$hash\",\"name\":\"$name\",\"version\":\"$version\"}"
          done < manifest.txt
